version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitor
    depends_on:
      - node-exporter
      - dvwa
      - blackbox-exporter

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - monitor
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor
    depends_on:
      - prometheus

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - 8080:80
    networks:
      - monitor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - 9115:9115
    networks:
      - monitor

  monitor-bot:
    build:
      context: ./monitor-bot  # Đường dẫn tới thư mục chứa Dockerfile và monitor_bot.py
    networks:
      - monitor
    restart: always
    volumes:
      - ./monitor-bot/monitor_bot.py:/app/monitor_bot.py  # Mount trực tiếp file monitor_bot.py vào container
networks:
  monitor:

